[package]

name = "influx"
version = "0.0.1"
authors = ["Richard Dodd <richard.o.dodd@gmail.com>"]

[dependencies]
hyper = "*"
regex = "*"
regex_macros = "*"
time = "*"
url = "*"
rustc-serialize = "*"
